//! Walker accuracy fixture — pins the deterministic output of every
//! walker to a golden SHA-256.
//!
//! Walker output is a pure function of `(model weights, config)`. The
//! mock model in `walker::test_fixture` is byte-deterministic (all
//! weights driven by `random_f32(n, seed)`), so re-running the same
//! walker with the same config must produce byte-identical edges /
//! vectors. This test asserts that contract: any change in the walker
//! arithmetic, ordering, or rounding will flip the hash and fail loudly.
//!
//! When intentionally changing walker output (e.g. fixing a bug,
//! tightening a threshold), update the golden constant — never silently
//! swallow a mismatch.
//!
//! Hashed payloads are stable canonical forms:
//!   weight walker → `subject\trelation\tobject\tlayer\tfeature\tconfidence:.6\n`
//!   attention walker → same shape, with `head` instead of `feature`
//!   vector extractor → the full NDJSON file, sorted lines, hashed bytes

use std::path::Path;

use sha2::{Digest, Sha256};

use larql_core::Graph;
use larql_vindex::walker::{
    attention_walker::AttentionWalker,
    test_fixture::create_mock_model,
    vector_extractor::{ExtractConfig, SilentExtractCallbacks, VectorExtractor},
    weight_walker::{SilentWalkCallbacks, WalkConfig, WeightWalker},
};

fn fixture(slug: &str) -> std::path::PathBuf {
    let dir = std::env::temp_dir().join(format!("larql_accuracy_{slug}"));
    let _ = std::fs::remove_dir_all(&dir);
    create_mock_model(&dir);
    dir
}

fn cleanup(dir: &Path) {
    let _ = std::fs::remove_dir_all(dir);
}

fn sha256_hex(bytes: &[u8]) -> String {
    let mut h = Sha256::new();
    h.update(bytes);
    let out = h.finalize();
    out.iter().map(|b| format!("{b:02x}")).collect()
}

/// Canonical edge form: tab-separated fields, sorted, one edge per line.
fn canonicalise_edges(graph: &Graph, layer_field: &str, feature_field: &str) -> Vec<u8> {
    let mut lines: Vec<String> = graph
        .edges()
        .iter()
        .map(|e| {
            let m = e.metadata.as_ref().unwrap();
            let layer = m.get(layer_field).and_then(|v| v.as_u64()).unwrap_or(0);
            let feat = m.get(feature_field).and_then(|v| v.as_u64()).unwrap_or(0);
            format!(
                "{}\t{}\t{}\t{}\t{}\t{:.6}",
                e.subject, e.relation, e.object, layer, feat, e.confidence
            )
        })
        .collect();
    lines.sort();
    let mut out = lines.join("\n").into_bytes();
    out.push(b'\n');
    out
}

// ── Goldens ──────────────────────────────────────────────────────────────
//
// Generated by running the test once with `LARQL_PRINT_GOLDEN=1`. To
// regenerate after an intentional walker change:
//   LARQL_PRINT_GOLDEN=1 cargo test -p larql-vindex --test \
//     test_walker_accuracy -- --nocapture
// then paste the printed hex strings below.

const GOLDEN_WEIGHT_WALKER_LAYER0: &str =
    "53bbb2110e2767a9683a872067ae4eb8253ee040db91cd4ba95d91e8540487dd";
const GOLDEN_ATTENTION_WALKER_LAYER0: &str =
    "c3f76f8f6dd590534eda2193786459f178c3af7a44ee8862ec11a69e09ca1905";
// Regenerated 2026-05-10: the canonicalisation now strips the `_header`
// record so the wall-clock `extraction_date` field doesn't make the
// golden drift every day. The hash covers only walker content rows.
const GOLDEN_VECTOR_EXTRACTOR_FFN_DOWN_LAYER0: &str =
    "8b5e221b150147ed40b0cfa67fdfc264e0628ab6cd6c59c2f9419e9350589b83";

fn check_or_print(label: &str, actual: &str, golden: &str) {
    if std::env::var("LARQL_PRINT_GOLDEN").is_ok() {
        eprintln!("{label} = {actual:?}");
        return;
    }
    assert_eq!(
        actual, golden,
        "{label}: walker output drifted — review the change and update the golden if intentional"
    );
}

#[test]
fn weight_walker_layer0_byte_identical() {
    let dir = fixture("ww");
    let walker = WeightWalker::load(dir.to_str().unwrap()).unwrap();
    let cfg = WalkConfig {
        top_k: 3,
        min_score: 0.0,
    };
    let mut g = Graph::new();
    let mut cb = SilentWalkCallbacks;
    walker.walk_layer(0, &cfg, &mut g, &mut cb).unwrap();

    let bytes = canonicalise_edges(&g, "layer", "feature");
    let hex = sha256_hex(&bytes);
    check_or_print("weight_walker_layer0", &hex, GOLDEN_WEIGHT_WALKER_LAYER0);

    cleanup(&dir);
}

#[test]
fn attention_walker_layer0_byte_identical() {
    let dir = fixture("aw");
    let walker = AttentionWalker::load(dir.to_str().unwrap()).unwrap();
    let cfg = WalkConfig {
        top_k: 2,
        min_score: 0.0,
    };
    let mut g = Graph::new();
    let mut cb = SilentWalkCallbacks;
    walker.walk_layer(0, &cfg, &mut g, &mut cb).unwrap();

    let bytes = canonicalise_edges(&g, "layer", "head");
    let hex = sha256_hex(&bytes);
    check_or_print(
        "attention_walker_layer0",
        &hex,
        GOLDEN_ATTENTION_WALKER_LAYER0,
    );

    cleanup(&dir);
}

#[test]
fn vector_extractor_ffn_down_byte_identical() {
    let dir = fixture("vex");
    let extractor = VectorExtractor::load(dir.to_str().unwrap()).unwrap();
    let out = dir.join("output");
    std::fs::create_dir_all(&out).unwrap();

    let cfg = ExtractConfig {
        components: vec!["ffn_down".into()],
        layers: Some(vec![0]),
        top_k: 3,
    };
    let mut cb = SilentExtractCallbacks;
    extractor.extract_all(&cfg, &out, false, &mut cb).unwrap();

    let path = out.join("ffn_down.vectors.jsonl");
    let text = std::fs::read_to_string(&path).unwrap();
    // Sort lines so re-ordering of feature loops doesn't break the
    // golden — content is what we care about. Skip the `_header`
    // record: it carries `extraction_date` (today's date), which would
    // otherwise drift the hash every wall-clock day.
    let mut lines: Vec<&str> = text
        .lines()
        .filter(|l| !l.contains("\"_header\":true"))
        .collect();
    lines.sort();
    let canonical = lines.join("\n");
    let hex = sha256_hex(canonical.as_bytes());
    check_or_print(
        "vector_extractor_ffn_down_layer0",
        &hex,
        GOLDEN_VECTOR_EXTRACTOR_FFN_DOWN_LAYER0,
    );

    cleanup(&dir);
}

#[test]
fn fixture_is_deterministic_across_runs() {
    // Build the fixture twice and verify the safetensors bytes match.
    // If this test fails the goldens above are unreliable — every
    // walker test depends on `create_mock_model` being a pure function.
    let dir_a = fixture("det_a");
    let dir_b = fixture("det_b");
    let bytes_a = std::fs::read(dir_a.join("model.safetensors")).unwrap();
    let bytes_b = std::fs::read(dir_b.join("model.safetensors")).unwrap();
    assert_eq!(bytes_a, bytes_b, "fixture is not deterministic");
    cleanup(&dir_a);
    cleanup(&dir_b);
}
